#!/usr/bin/env python3
"""Keep the workspace repo manifest and generated ignore rules in sync."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "repos.yaml"
MANAGED_BEGIN = "# BEGIN managed repo folders"
MANAGED_END = "# END managed repo folders"
MANAGED_NOTE = "# Generated by .workspace/sync-repos.py from repos.yaml."

README = ROOT / "README.md"
MAP_BEGIN = "<!-- BEGIN managed repo map -->"
MAP_END = "<!-- END managed repo map -->"
MAP_NOTE = "<!-- Generated by .workspace/sync-repos.py from repos.yaml. Do not edit by hand. -->"
README_INTRO = """# best

My life-optimization workspace: a meta-repo where each leaf folder in the map below is
its own Git repository (not a submodule). Their files aren't tracked here — because git
won't reach across a nested `.git`, the parent shows only this map, and each link opens
the child repo where its files actually live.

Regenerated from `repos.yaml` by `.workspace/sync-repos.py`; run it after adding or
removing a nested repo."""


def run_git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def q(value: str | None) -> str:
    if value is None:
        return "null"
    return json.dumps(value)


def unq(value: str) -> str | None:
    value = value.strip()
    if value == "null":
        return None
    return json.loads(value)


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def discover_repos() -> list[Path]:
    repos: list[Path] = []
    for current, dirs, files in os.walk(ROOT):
        path = Path(current)

        if ".git" in dirs:
            dirs.remove(".git")

        marker = path / ".git"
        if path != ROOT and (marker.is_dir() or marker.is_file()):
            repos.append(path)

        dirs[:] = [d for d in dirs if d not in {".git", "__pycache__"}]

    return sorted(repos, key=lambda p: rel(p))


def origin_url(repo: Path) -> str | None:
    result = run_git(repo, "remote", "get-url", "origin")
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def current_branch(repo: Path) -> str | None:
    result = run_git(repo, "branch", "--show-current")
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def nearest_parent(repo: Path, repos: list[Path]) -> Path:
    parent = ROOT
    for candidate in [ROOT, *repos]:
        if candidate == repo:
            continue
        try:
            repo.relative_to(candidate)
        except ValueError:
            continue
        if len(candidate.parts) > len(parent.parts):
            parent = candidate
    return parent


def build_manifest(repos: list[Path]) -> str:
    lines = [
        "# Generated by .workspace/sync-repos.py. Do not edit by hand.",
        "# Run `.workspace/sync-repos.py` after adding or removing nested Git repos.",
        "repos:",
    ]
    for repo in repos:
        parent = nearest_parent(repo, repos)
        lines.extend(
            [
                f"  - path: {q(rel(repo))}",
                f"    parent: {q('.' if parent == ROOT else rel(parent))}",
                f"    remote: {q(origin_url(repo))}",
                f"    branch: {q(current_branch(repo))}",
            ]
        )
    return "\n".join(lines) + "\n"


def parse_manifest(text: str) -> list[dict[str, str | None]]:
    entries: list[dict[str, str | None]] = []
    entry: dict[str, str | None] | None = None
    field = re.compile(r"^\s{4}([a-z_]+):\s*(.+)$")

    for line in text.splitlines():
        if line.startswith("  - path: "):
            if entry:
                entries.append(entry)
            entry = {"path": unq(line.split(":", 1)[1])}
            continue

        if entry is None:
            continue

        match = field.match(line)
        if match:
            entry[match.group(1)] = unq(match.group(2))

    if entry:
        entries.append(entry)
    return entries


def parent_patterns(entries: list[dict[str, str | None]]) -> dict[Path, list[str]]:
    grouped: dict[Path, list[str]] = {}
    for entry in entries:
        raw_path = entry.get("path")
        if not raw_path:
            continue
        raw_parent = entry.get("parent") or "."
        parent = ROOT if raw_parent == "." else ROOT / raw_parent
        child = Path(raw_path)
        if raw_parent != ".":
            child = child.relative_to(raw_parent)
        grouped.setdefault(parent, []).append(child.as_posix() + "/")
    return {parent: sorted(set(patterns)) for parent, patterns in grouped.items()}


def replace_managed_block(existing: str, patterns: list[str]) -> str:
    block_re = re.compile(
        rf"\n?{re.escape(MANAGED_BEGIN)}\n.*?{re.escape(MANAGED_END)}\n?",
        re.DOTALL,
    )
    base = block_re.sub("\n", existing).strip("\n")
    block = "\n".join([MANAGED_BEGIN, MANAGED_NOTE, *patterns, MANAGED_END])
    if base:
        return f"{base}\n\n{block}\n"
    return f"{block}\n"


def desired_ignores(entries: list[dict[str, str | None]]) -> dict[Path, str]:
    desired: dict[Path, str] = {}
    for parent, patterns in parent_patterns(entries).items():
        ignore = parent / ".gitignore"
        existing = ignore.read_text() if ignore.exists() else ""
        desired[ignore] = replace_managed_block(existing, patterns)
    return desired


def browsable(remote: str | None) -> str | None:
    if not remote:
        return None
    return re.sub(r"\.git$", "", remote)


def build_repo_map(entries: list[dict[str, str | None]]) -> str:
    tree: dict[str, dict] = {}
    for entry in entries:
        raw_path = entry.get("path")
        if not raw_path:
            continue
        node = tree
        parts = Path(raw_path).parts
        for i, part in enumerate(parts):
            child = node.setdefault(part, {"children": {}, "remote": None})
            if i == len(parts) - 1:
                child["remote"] = entry.get("remote")
            node = child["children"]

    lines: list[str] = []

    def render(children: dict[str, dict], depth: int) -> None:
        for name in sorted(children):
            info = children[name]
            indent = "  " * depth
            url = browsable(info["remote"])
            if url:
                lines.append(f"{indent}- [{name}/]({url})")
            else:
                lines.append(f"{indent}- {name}/")
            render(info["children"], depth + 1)

    render(tree, 0)
    return "\n".join(lines)


def desired_readme(entries: list[dict[str, str | None]]) -> str:
    block = "\n".join(
        [MAP_BEGIN, MAP_NOTE, "", "## Nested repositories", "", build_repo_map(entries), MAP_END]
    )
    existing = README.read_text() if README.exists() else ""
    block_re = re.compile(
        rf"\n?{re.escape(MAP_BEGIN)}\n.*?{re.escape(MAP_END)}\n?",
        re.DOTALL,
    )
    base = block_re.sub("\n", existing).strip("\n")
    if not base:
        base = README_INTRO.strip("\n")
    return f"{base}\n\n{block}\n"


def find_gitmodules() -> list[Path]:
    found: list[Path] = []
    for path in ROOT.rglob(".gitmodules"):
        if ".git" not in path.parts:
            found.append(path)
    return sorted(found)


def find_gitlinks(repos: list[Path]) -> dict[Path, list[str]]:
    gitlinks: dict[Path, list[str]] = {}
    for repo in [ROOT, *repos]:
        result = run_git(repo, "ls-files", "-s")
        if result.returncode != 0:
            continue
        links = [
            line.rsplit("\t", 1)[-1]
            for line in result.stdout.splitlines()
            if line.startswith("160000 ")
        ]
        if links:
            gitlinks[repo] = links
    return gitlinks


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text() if path.exists() else None
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def write() -> int:
    repos = discover_repos()
    manifest = build_manifest(repos)
    changed = [str(MANIFEST.relative_to(ROOT))] if write_if_changed(MANIFEST, manifest) else []

    entries = parse_manifest(manifest)
    for path, content in desired_ignores(entries).items():
        if write_if_changed(path, content):
            changed.append(path.relative_to(ROOT).as_posix())

    if write_if_changed(README, desired_readme(entries)):
        changed.append(README.relative_to(ROOT).as_posix())

    if changed:
        print("updated:")
        for path in changed:
            print(f"  {path}")
    else:
        print("repos.yaml and generated .gitignore blocks are current")
    return 0


def check() -> int:
    repos = discover_repos()
    expected_manifest = build_manifest(repos)
    failures: list[str] = []

    if not MANIFEST.exists():
        failures.append("repos.yaml is missing; run `.workspace/sync-repos.py`.")
    elif MANIFEST.read_text() != expected_manifest:
        failures.append("repos.yaml is stale; run `.workspace/sync-repos.py`.")

    manifest_text = MANIFEST.read_text() if MANIFEST.exists() else expected_manifest
    manifest_entries = parse_manifest(manifest_text)
    for path, expected in desired_ignores(manifest_entries).items():
        if not path.exists() or path.read_text() != expected:
            failures.append(
                f"{path.relative_to(ROOT).as_posix()} generated block is stale; "
                "run `.workspace/sync-repos.py`."
            )

    if not README.exists() or README.read_text() != desired_readme(manifest_entries):
        failures.append("README.md repo map is stale; run `.workspace/sync-repos.py`.")

    gitmodules = find_gitmodules()
    if gitmodules:
        paths = ", ".join(path.relative_to(ROOT).as_posix() for path in gitmodules)
        failures.append(f"submodule metadata remains: {paths}")

    gitlinks = find_gitlinks(repos)
    for repo, links in gitlinks.items():
        label = "." if repo == ROOT else repo.relative_to(ROOT).as_posix()
        failures.append(f"{label} still tracks gitlinks: {', '.join(links)}")

    if failures:
        for failure in failures:
            print(f"repo sync check: {failure}", file=sys.stderr)
        return 1

    print("repo sync check passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if repos.yaml, generated ignores, or submodule state are stale",
    )
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
