#!/usr/bin/env python3
"""Keep the workspace repo manifest and generated ignore rules in sync."""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "repos.yaml"
MANAGED_BEGIN = "# BEGIN managed repo folders"
MANAGED_END = "# END managed repo folders"
MANAGED_NOTE = "# Generated by .workspace/sync-repos.py from repos.yaml."

PRIVATE_PATHS = ROOT / ".workspace" / "private-paths"
MAP_BEGIN = "<!-- BEGIN managed repo map -->"
MAP_END = "<!-- END managed repo map -->"
MAP_NOTE = "<!-- Generated by .workspace/sync-repos.py from repos.yaml. Do not edit by hand. -->"
SUBREPO_NOTE = (
    "These folders are separate Git repos, not tracked here — git can't reach across a "
    "nested `.git`, so open a link to see a folder's files. (Private links 404 without access.)"
)
ROOT_INTRO = """# best

My life-optimization workspace: a meta-repo of mostly plain folders (browse them here)
plus a few nested folders that are separate Git repos. Those sub-repos are listed below —
git can't reach across a nested `.git`, so their files live behind the links, not here."""


def run_git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def q(value: str | None) -> str:
    if value is None:
        return "null"
    return json.dumps(value)


def unq(value: str) -> str | None:
    value = value.strip()
    if value == "null":
        return None
    return json.loads(value)


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def discover_repos() -> list[Path]:
    repos: list[Path] = []
    for current, dirs, files in os.walk(ROOT):
        path = Path(current)

        if ".git" in dirs:
            dirs.remove(".git")

        marker = path / ".git"
        if path != ROOT and (marker.is_dir() or marker.is_file()):
            repos.append(path)

        dirs[:] = [d for d in dirs if d not in {".git", "__pycache__"}]

    return sorted(repos, key=lambda p: rel(p))


def origin_url(repo: Path) -> str | None:
    result = run_git(repo, "remote", "get-url", "origin")
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def current_branch(repo: Path) -> str | None:
    result = run_git(repo, "branch", "--show-current")
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def nearest_parent(repo: Path, repos: list[Path]) -> Path:
    parent = ROOT
    for candidate in [ROOT, *repos]:
        if candidate == repo:
            continue
        try:
            repo.relative_to(candidate)
        except ValueError:
            continue
        if len(candidate.parts) > len(parent.parts):
            parent = candidate
    return parent


def build_manifest(repos: list[Path]) -> str:
    lines = [
        "# Generated by .workspace/sync-repos.py. Do not edit by hand.",
        "# Run `.workspace/sync-repos.py` after adding or removing nested Git repos.",
        "repos:",
    ]
    for repo in repos:
        parent = nearest_parent(repo, repos)
        lines.extend(
            [
                f"  - path: {q(rel(repo))}",
                f"    parent: {q('.' if parent == ROOT else rel(parent))}",
                f"    remote: {q(origin_url(repo))}",
                f"    branch: {q(current_branch(repo))}",
            ]
        )
    return "\n".join(lines) + "\n"


def parse_manifest(text: str) -> list[dict[str, str | None]]:
    entries: list[dict[str, str | None]] = []
    entry: dict[str, str | None] | None = None
    field = re.compile(r"^\s{4}([a-z_]+):\s*(.+)$")

    for line in text.splitlines():
        if line.startswith("  - path: "):
            if entry:
                entries.append(entry)
            entry = {"path": unq(line.split(":", 1)[1])}
            continue

        if entry is None:
            continue

        match = field.match(line)
        if match:
            entry[match.group(1)] = unq(match.group(2))

    if entry:
        entries.append(entry)
    return entries


def parent_patterns(entries: list[dict[str, str | None]]) -> dict[Path, list[str]]:
    grouped: dict[Path, list[str]] = {}
    for entry in entries:
        raw_path = entry.get("path")
        if not raw_path:
            continue
        raw_parent = entry.get("parent") or "."
        parent = ROOT if raw_parent == "." else ROOT / raw_parent
        child = Path(raw_path)
        if raw_parent != ".":
            child = child.relative_to(raw_parent)
        grouped.setdefault(parent, []).append(child.as_posix() + "/")
    return {parent: sorted(set(patterns)) for parent, patterns in grouped.items()}


def replace_managed_block(existing: str, patterns: list[str]) -> str:
    block_re = re.compile(
        rf"\n?{re.escape(MANAGED_BEGIN)}\n.*?{re.escape(MANAGED_END)}\n?",
        re.DOTALL,
    )
    base = block_re.sub("\n", existing).strip("\n")
    block = "\n".join([MANAGED_BEGIN, MANAGED_NOTE, *patterns, MANAGED_END])
    if base:
        return f"{base}\n\n{block}\n"
    return f"{block}\n"


def desired_ignores(entries: list[dict[str, str | None]]) -> dict[Path, str]:
    desired: dict[Path, str] = {}
    for parent, patterns in parent_patterns(entries).items():
        ignore = parent / ".gitignore"
        existing = ignore.read_text() if ignore.exists() else ""
        desired[ignore] = replace_managed_block(existing, patterns)
    return desired


def browsable(remote: str | None) -> str | None:
    if not remote:
        return None
    return re.sub(r"\.git$", "", remote)


def owner_repo(remote: str | None) -> str | None:
    if not remote:
        return None
    match = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?/?$", remote)
    return match.group(1) if match else remote


def private_prefixes() -> list[str]:
    if not PRIVATE_PATHS.exists():
        return []
    prefixes: list[str] = []
    for line in PRIVATE_PATHS.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            prefixes.append(line.strip("/"))
    return prefixes


def is_private(path: str, private: list[str]) -> bool:
    # Exact match: visibility reflects the linked repo itself, not its container. A
    # private repo's own path is listed; a public (e.g. third-party) repo nested inside
    # a private one is still its own accessible repo, so it isn't marked private.
    return path in private


def build_subrepo_table(
    children: list[dict[str, str | None]], parent: str, prefixes: list[str]
) -> str:
    rows = ["| Folder | Visibility | Repository |", "|---|---|---|"]
    for entry in sorted(children, key=lambda e: e["path"] or ""):
        full = entry["path"] or ""
        rel = full if parent == "." else Path(full).relative_to(parent).as_posix()
        url = browsable(entry.get("remote"))
        slug = owner_repo(entry.get("remote")) or rel
        link = f"[{slug}]({url})" if url else slug
        vis = "🔒 private" if is_private(full, prefixes) else "public"
        rows.append(f"| `{rel}/` | {vis} | {link} |")
    return "\n".join(rows)


def readme_path(parent: str) -> Path:
    return README_ROOT if parent == "." else ROOT / parent / "README.md"


README_ROOT = ROOT / "README.md"


def desired_readmes(entries: list[dict[str, str | None]]) -> dict[Path, str]:
    prefixes = private_prefixes()
    by_parent: dict[str, list[dict[str, str | None]]] = {}
    for entry in entries:
        if not entry.get("path"):
            continue
        by_parent.setdefault(entry.get("parent") or ".", []).append(entry)

    block_re = re.compile(
        rf"\n?{re.escape(MAP_BEGIN)}\n.*?{re.escape(MAP_END)}\n?",
        re.DOTALL,
    )
    desired: dict[Path, str] = {}
    for parent, children in by_parent.items():
        readme = readme_path(parent)
        block = "\n".join(
            [
                MAP_BEGIN,
                MAP_NOTE,
                "",
                "## Sub-repositories",
                "",
                SUBREPO_NOTE,
                "",
                build_subrepo_table(children, parent, prefixes),
                MAP_END,
            ]
        )
        existing = readme.read_text() if readme.exists() else ""
        base = block_re.sub("\n", existing).strip("\n")
        if not base:
            base = ROOT_INTRO.strip("\n") if parent == "." else f"# {Path(parent).name}"
        desired[readme] = f"{base}\n\n{block}\n"
    return desired


def desired_gitkeeps(entries: list[dict[str, str | None]]) -> set[Path]:
    """A `.gitkeep` for any folder whose only visible content is nested repos, so the
    path down to a sub-repo never vanishes (git tracks no empty directory)."""
    by_folder: dict[Path, set[str]] = {}
    for entry in entries:
        child = Path(entry["path"] or "")
        by_folder.setdefault(child.parent, set()).add(child.name)

    keeps: set[Path] = set()
    for rel_folder, subrepos in by_folder.items():
        if rel_folder == Path("."):
            continue
        folder = ROOT / rel_folder
        if not folder.is_dir():
            continue
        others = [
            item.name
            for item in folder.iterdir()
            if item.name not in subrepos
            and item.name != ".gitkeep"
            and not item.name.startswith(".")
        ]
        if not others:
            keeps.add(folder / ".gitkeep")
    return keeps


def find_gitmodules() -> list[Path]:
    found: list[Path] = []
    for path in ROOT.rglob(".gitmodules"):
        if ".git" not in path.parts:
            found.append(path)
    return sorted(found)


def find_gitlinks(repos: list[Path]) -> dict[Path, list[str]]:
    gitlinks: dict[Path, list[str]] = {}
    for repo in [ROOT, *repos]:
        result = run_git(repo, "ls-files", "-s")
        if result.returncode != 0:
            continue
        links = [
            line.rsplit("\t", 1)[-1]
            for line in result.stdout.splitlines()
            if line.startswith("160000 ")
        ]
        if links:
            gitlinks[repo] = links
    return gitlinks


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text() if path.exists() else None
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def write() -> int:
    repos = discover_repos()
    manifest = build_manifest(repos)
    changed = [str(MANIFEST.relative_to(ROOT))] if write_if_changed(MANIFEST, manifest) else []

    entries = parse_manifest(manifest)
    for path, content in desired_ignores(entries).items():
        if write_if_changed(path, content):
            changed.append(path.relative_to(ROOT).as_posix())

    for path, content in desired_readmes(entries).items():
        if write_if_changed(path, content):
            changed.append(path.relative_to(ROOT).as_posix())

    for keep in desired_gitkeeps(entries):
        if not keep.exists():
            keep.write_text("")
            changed.append(keep.relative_to(ROOT).as_posix())

    if changed:
        print("updated:")
        for path in changed:
            print(f"  {path}")
    else:
        print("repos.yaml and generated .gitignore blocks are current")
    return 0


def check() -> int:
    repos = discover_repos()
    expected_manifest = build_manifest(repos)
    failures: list[str] = []

    if not MANIFEST.exists():
        failures.append("repos.yaml is missing; run `.workspace/sync-repos.py`.")
    elif MANIFEST.read_text() != expected_manifest:
        failures.append("repos.yaml is stale; run `.workspace/sync-repos.py`.")

    manifest_text = MANIFEST.read_text() if MANIFEST.exists() else expected_manifest
    manifest_entries = parse_manifest(manifest_text)
    for path, expected in desired_ignores(manifest_entries).items():
        if not path.exists() or path.read_text() != expected:
            failures.append(
                f"{path.relative_to(ROOT).as_posix()} generated block is stale; "
                "run `.workspace/sync-repos.py`."
            )

    for path, expected in desired_readmes(manifest_entries).items():
        if not path.exists() or path.read_text() != expected:
            failures.append(
                f"{path.relative_to(ROOT).as_posix()} sub-repo map is stale; "
                "run `.workspace/sync-repos.py`."
            )

    for keep in desired_gitkeeps(manifest_entries):
        if not keep.exists():
            failures.append(
                f"{keep.relative_to(ROOT).as_posix()} is missing; "
                "run `.workspace/sync-repos.py`."
            )

    gitmodules = find_gitmodules()
    if gitmodules:
        paths = ", ".join(path.relative_to(ROOT).as_posix() for path in gitmodules)
        failures.append(f"submodule metadata remains: {paths}")

    gitlinks = find_gitlinks(repos)
    for repo, links in gitlinks.items():
        label = "." if repo == ROOT else repo.relative_to(ROOT).as_posix()
        failures.append(f"{label} still tracks gitlinks: {', '.join(links)}")

    if failures:
        for failure in failures:
            print(f"repo sync check: {failure}", file=sys.stderr)
        return 1

    print("repo sync check passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if repos.yaml, generated ignores, or submodule state are stale",
    )
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
