#!/usr/bin/env python3
"""Build the site from the guide's markdown files.

No dependencies. Produces two artifacts:
  site/index.html     — the guide + live sidebar assistant (markdown rendered
                        in-browser with marked.js)
  site/api/_guide.js  — the assistant's system prompt (assistant/system-prompt.md
                        with the full guide injected), imported by api/assistant.js

Re-run after editing any .md file:  python3 site/build.py
Deploy: vercel deploy (from site/). The assistant route needs ANTHROPIC_API_KEY;
feedback persists to Vercel Blob if BLOB_READ_WRITE_TOKEN is set, else runtime logs.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "site" / "index.html"
GUIDE_JS = ROOT / "site" / "api" / "_guide.js"

# (path relative to guide root, sidebar label, section)
PAGES = [
    ("00-start-here.md", "Start here", "Guide"),
    ("01-cowork.md", "1 · Claude Cowork", "Guide"),
    ("02-claude-code.md", "2 · Claude Code", "Guide"),
    ("03-power-ups.md", "3 · Power-ups", "Guide"),
    ("04-now-what.md", "Now what", "Guide"),
    ("decisions/account.md", "Account & tier", "Decisions"),
    ("decisions/which-model.md", "Which model", "Decisions"),
    ("decisions/dictation.md", "Talking to Claude", "Decisions"),
    ("decisions/trust-and-permissions.md", "Trust & permissions", "Decisions"),
    ("decisions/connectors.md", "Which connectors", "Decisions"),
    ("decisions/cowork-vs-code.md", "Cowork vs Code", "Decisions"),
    ("decisions/interface.md", "How to run Code", "Decisions"),
    ("decisions/workspace-access.md", "Workspace access", "Decisions"),
]

content = {}
for rel, _, _ in PAGES:
    content[rel] = (ROOT / rel).read_text(encoding="utf-8")

nav = {}
for rel, label, section in PAGES:
    nav.setdefault(section, []).append({"path": rel, "label": label})

DATA = json.dumps({"content": content, "nav": nav}, ensure_ascii=False)

# ---- system prompt for the API route -------------------------------------
prompt_md = (ROOT / "assistant" / "system-prompt.md").read_text(encoding="utf-8")
# Drop the editorial preamble (everything before the first ---), inject the guide.
prompt_body = prompt_md.split("\n---\n", 1)[1].strip()
guide_text = "\n\n".join(
    f"===== {label} ({rel}) =====\n\n{content[rel]}" for rel, label, _ in PAGES
)
system_prompt = "\n".join(
    guide_text if "{{GUIDE}}" in line else line for line in prompt_body.splitlines()
)
# CommonJS on purpose: Vercel compiles api/*.js to CJS, which can't require ESM.
GUIDE_JS.parent.mkdir(exist_ok=True)
GUIDE_JS.write_text(
    "// Generated by site/build.py — do not edit.\n"
    f"module.exports.SYSTEM_PROMPT = {json.dumps(system_prompt, ensure_ascii=False)};\n",
    encoding="utf-8",
)

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Claude On-Ramp</title>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<style>
  :root {
    --bg: #faf9f7; --fg: #201d1a; --muted: #6b645c; --line: #e7e2db;
    --accent: #b8532a; --card: #fff; --code: #f2efe9;
  }
  @media (prefers-color-scheme: dark) {
    :root { --bg:#1a1817; --fg:#e9e4dd; --muted:#a49b90; --line:#333029;
            --accent:#e07850; --card:#221f1d; --code:#2a2723; }
  }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--fg);
    font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; }
  .app { display:grid; grid-template-columns:250px minmax(0,1fr) 340px;
    min-height:100vh; }
  nav { border-right:1px solid var(--line); padding:24px 18px; position:sticky;
    top:0; height:100vh; overflow:auto; }
  nav h1 { font-size:15px; letter-spacing:.02em; margin:0 0 20px; }
  nav .sec { font-size:11px; text-transform:uppercase; letter-spacing:.08em;
    color:var(--muted); margin:22px 0 8px; }
  nav a { display:block; padding:5px 8px; margin:1px 0; border-radius:6px;
    color:var(--fg); text-decoration:none; font-size:14px; }
  nav a:hover { background:var(--code); }
  nav a.active { background:var(--accent); color:#fff; }
  main { padding:56px 64px; max-width:760px; }
  main h1 { font-size:30px; line-height:1.2; margin:0 0 24px; }
  main h2 { font-size:21px; margin:38px 0 12px; }
  main h3 { font-size:17px; margin:26px 0 8px; }
  main a { color:var(--accent); }
  main code { background:var(--code); padding:1px 6px; border-radius:5px;
    font-size:.9em; }
  main pre { background:var(--code); padding:14px 16px; border-radius:10px;
    overflow:auto; }
  main pre code { background:none; padding:0; }
  main table { border-collapse:collapse; width:100%; margin:16px 0; font-size:14px; }
  main th,main td { border:1px solid var(--line); padding:7px 10px; text-align:left; }
  main blockquote { border-left:3px solid var(--accent); margin:16px 0;
    padding:2px 18px; color:var(--muted); }
  main li.done { color:var(--muted); text-decoration:line-through;
    text-decoration-color:var(--accent); }
  main input[type=checkbox] { accent-color:var(--accent); cursor:pointer;
    margin-right:8px; width:15px; height:15px; vertical-align:-2px; }
  details { background:var(--card); border:1px solid var(--line);
    border-radius:10px; padding:2px 16px; margin:14px 0; }
  details summary { cursor:pointer; padding:10px 0; font-weight:600;
    color:var(--accent); }
  details[open] summary { border-bottom:1px solid var(--line); margin-bottom:10px; }
  aside { border-left:1px solid var(--line); padding:20px; position:sticky;
    top:0; height:100vh; display:flex; flex-direction:column; }
  aside h2 { font-size:14px; margin:0 0 4px; }
  aside .sub { font-size:12px; color:var(--muted); margin-bottom:12px; }
  .chat { flex:1; overflow:auto; background:var(--card); border:1px solid var(--line);
    border-radius:10px; padding:12px; font-size:13px; display:flex;
    flex-direction:column; gap:10px; }
  .msg { max-width:100%; line-height:1.5; }
  .msg.user { align-self:flex-end; background:var(--code); border-radius:10px;
    padding:7px 11px; white-space:pre-wrap; max-width:85%; }
  .msg.assistant p:first-child { margin-top:0; }
  .msg.assistant p:last-child { margin-bottom:0; }
  .msg.assistant code { background:var(--code); padding:1px 5px; border-radius:4px; }
  .msg.assistant pre { background:var(--code); padding:10px; border-radius:8px;
    overflow:auto; }
  .msg img.shot { max-width:120px; border-radius:6px; border:1px solid var(--line);
    display:block; margin-top:5px; }
  .msg .status { color:var(--muted); font-style:italic; }
  .compose { margin-top:10px; }
  .attach-strip { display:flex; gap:6px; margin-bottom:6px; }
  .attach-strip .thumb { position:relative; }
  .attach-strip img { height:44px; border-radius:6px; border:1px solid var(--line); }
  .attach-strip button { position:absolute; top:-6px; right:-6px; width:18px;
    height:18px; border-radius:50%; border:none; background:var(--fg);
    color:var(--bg); font-size:11px; line-height:1; cursor:pointer; padding:0; }
  .row { display:flex; gap:8px; }
  .row textarea { flex:1; padding:9px 11px; border:1px solid var(--line);
    border-radius:8px; background:var(--bg); color:var(--fg); font-size:13px;
    font-family:inherit; resize:none; height:42px; }
  .row button { padding:0 12px; border:none; border-radius:8px;
    background:var(--accent); color:#fff; font-size:13px; cursor:pointer; }
  .row button.ghost { background:none; border:1px solid var(--line);
    color:var(--muted); font-size:15px; }
  .hint { font-size:11px; color:var(--muted); margin-top:8px; line-height:1.5; }
  .didntwork { margin:40px 0 0; padding-top:16px; border-top:1px solid var(--line);
    font-size:13px; color:var(--muted); }
  .didntwork button { background:none; border:1px solid var(--line);
    color:var(--muted); border-radius:20px; padding:5px 12px; cursor:pointer;
    font-size:12px; }
  .didntwork .form { margin-top:10px; display:flex; gap:8px; }
  .didntwork input { flex:1; padding:7px 10px; border:1px solid var(--line);
    border-radius:8px; background:var(--bg); color:var(--fg); font-size:12px; }
  .didntwork .thanks { color:var(--accent); }
  @media (max-width:1100px){ .app{grid-template-columns:220px 1fr;} aside{display:none;} }
  @media (max-width:720px){ .app{grid-template-columns:1fr;} nav{display:none;} main{padding:28px 20px;} }
</style>
</head>
<body>
<div class="app">
  <nav id="nav"><h1>Claude On-Ramp</h1></nav>
  <main id="main"></main>
  <aside>
    <h2>Assistant</h2>
    <div class="sub">Stuck? Ask — this whole guide is loaded.</div>
    <div class="chat" id="chat"></div>
    <div class="compose">
      <div class="attach-strip" id="attachments"></div>
      <div class="row">
        <button class="ghost" title="Attach a screenshot"
          onclick="document.getElementById('file').click()">📎</button>
        <input type="file" id="file" accept="image/*" hidden>
        <textarea id="ask" placeholder="Describe what's happening — or paste a screenshot"></textarea>
        <button id="send">Send</button>
      </div>
      <div class="hint">Screenshots beat descriptions: <b>⌘⇧4</b> on Mac,
        <b>Win+Shift+S</b> on Windows, then paste here.</div>
    </div>
  </aside>
</div>
<script>
const DATA = __DATA__;
const {content, nav} = DATA;

function resolve(from, href){
  // resolve a relative .md link against the current page's directory
  const dir = from.includes('/') ? from.slice(0, from.lastIndexOf('/')) : '';
  const parts = (dir ? dir.split('/') : []);
  href.split('/').forEach(p=>{
    if(p==='..') parts.pop();
    else if(p!=='.'&&p!=='') parts.push(p);
  });
  return parts.join('/');
}

function buildNav(){
  const n = document.getElementById('nav');
  for(const sec in nav){
    const h = document.createElement('div'); h.className='sec'; h.textContent=sec;
    n.appendChild(h);
    nav[sec].forEach(item=>{
      const a=document.createElement('a'); a.textContent=item.label;
      a.href='#'+item.path; a.dataset.path=item.path; n.appendChild(a);
    });
  }
}

let currentPath = '00-start-here.md';

function pageContext(){
  const h1 = document.querySelector('main h1');
  return currentPath + (h1 ? ' — ' + h1.textContent : '');
}

function osName(){
  const p = navigator.platform || '', ua = navigator.userAgent || '';
  if(/Mac/i.test(p)) return 'Mac';
  if(/Win/i.test(p)) return 'Windows';
  return (p || 'unknown') + ' · ' + ua.slice(0, 60);
}

function sendFeedback(kind, note){
  fetch('api/feedback', {
    method:'POST', headers:{'content-type':'application/json'},
    body: JSON.stringify({kind, step: pageContext(), os: osName(), note: note||''})
  }).catch(()=>{});
}

function render(path){
  if(!content[path]) path='00-start-here.md';
  currentPath = path;
  const main=document.getElementById('main');
  main.innerHTML = marked.parse(content[path]);
  // make the "things to do" checklists real: enable, restore, persist
  main.querySelectorAll('input[type=checkbox]').forEach((box,i)=>{
    box.disabled=false;
    const key='onramp-check:'+path+':'+i;
    box.checked = localStorage.getItem(key)==='1';
    const li=box.closest('li'); if(li) li.classList.toggle('done', box.checked);
    box.onchange=()=>{
      localStorage.setItem(key, box.checked?'1':'0');
      if(li) li.classList.toggle('done', box.checked);
    };
  });
  // rewrite intra-guide .md links to hash routes
  main.querySelectorAll('a[href]').forEach(a=>{
    const href=a.getAttribute('href');
    if(href.endsWith('.md') || href.includes('.md#')){
      const clean=href.replace('#','');
      a.setAttribute('href', '#'+resolve(path, clean));
    }
  });
  const fb=document.createElement('div'); fb.className='didntwork';
  const btn=document.createElement('button');
  btn.textContent="This step didn't work for me";
  btn.onclick=()=>{
    const form=document.createElement('div'); form.className='form';
    form.innerHTML='<input placeholder="What happened? (optional)">'
      +'<button>Send</button>';
    fb.replaceChildren(form);
    const done=()=>{
      sendFeedback('didnt-work', form.querySelector('input').value);
      fb.innerHTML='<span class="thanks">Thanks — logged. Tell the assistant '
        +'what you see and it can likely unstick you now.</span>';
    };
    form.querySelector('button').onclick=done;
    form.querySelector('input').onkeydown=e=>{ if(e.key==='Enter') done(); };
    form.querySelector('input').focus();
  };
  fb.appendChild(btn);
  main.appendChild(fb);
  document.querySelectorAll('nav a').forEach(a=>
    a.classList.toggle('active', a.dataset.path===path));
  main.scrollTo?.(0,0); window.scrollTo(0,0);
}

// ---- assistant chat -------------------------------------------------------
const chat = document.getElementById('chat');
const ask = document.getElementById('ask');
const history = [];   // Anthropic-format messages
let pendingImages = []; // {media_type, data}
let busy = false;

function addBubble(role){
  const div=document.createElement('div');
  div.className='msg '+role;
  chat.appendChild(div);
  chat.scrollTop = chat.scrollHeight;
  return div;
}

function greet(){
  const g=addBubble('assistant');
  g.innerHTML="Hi — I have the full guide in front of me. Tell me what you're "
    +"trying to do, or paste a screenshot of what you're seeing, and I'll get "
    +"you to the next step.";
}

function drawAttachments(){
  const strip=document.getElementById('attachments');
  strip.replaceChildren(...pendingImages.map((img,i)=>{
    const d=document.createElement('div'); d.className='thumb';
    const im=document.createElement('img');
    im.src='data:'+img.media_type+';base64,'+img.data;
    const x=document.createElement('button'); x.textContent='×';
    x.onclick=()=>{ pendingImages.splice(i,1); drawAttachments(); };
    d.append(im,x); return d;
  }));
}

function addImage(file){
  // Downscale client-side so requests stay under Vercel's body limit.
  const img=new Image();
  img.onload=()=>{
    const MAX=1400, s=Math.min(1, MAX/Math.max(img.width, img.height));
    const c=document.createElement('canvas');
    c.width=Math.round(img.width*s); c.height=Math.round(img.height*s);
    c.getContext('2d').drawImage(img,0,0,c.width,c.height);
    const data=c.toDataURL('image/jpeg',0.85).split(',')[1];
    pendingImages.push({media_type:'image/jpeg', data});
    drawAttachments();
    URL.revokeObjectURL(img.src);
  };
  img.src=URL.createObjectURL(file);
}

ask.addEventListener('paste', e=>{
  for(const item of e.clipboardData.items)
    if(item.type.startsWith('image/')){ addImage(item.getAsFile()); e.preventDefault(); }
});
document.getElementById('file').onchange=e=>{
  if(e.target.files[0]) addImage(e.target.files[0]);
  e.target.value='';
};
ask.addEventListener('keydown', e=>{
  if(e.key==='Enter' && !e.shiftKey){ e.preventDefault(); send(); }
});
document.getElementById('send').onclick=()=>send();

async function send(){
  const text=ask.value.trim();
  if(busy || (!text && !pendingImages.length)) return;
  busy=true; ask.value='';

  const blocks=[
    ...pendingImages.map(i=>({type:'image',
      source:{type:'base64', media_type:i.media_type, data:i.data}})),
    ...(text ? [{type:'text', text}] : [])
  ];
  const u=addBubble('user');
  u.textContent=text;
  pendingImages.forEach(i=>{
    const im=document.createElement('img'); im.className='shot';
    im.src='data:'+i.media_type+';base64,'+i.data; u.appendChild(im);
  });
  pendingImages=[]; drawAttachments();
  history.push({role:'user', content:blocks});

  const a=addBubble('assistant');
  a.innerHTML='<span class="status">Thinking…</span>';
  let answer='', searched=false;
  try{
    const resp=await fetch('api/assistant', {
      method:'POST', headers:{'content-type':'application/json'},
      body: JSON.stringify({messages: history.slice(-20), page: pageContext()})
    });
    if(!resp.ok){
      const err=await resp.json().catch(()=>({}));
      throw new Error(err.error || ('HTTP '+resp.status));
    }
    const reader=resp.body.getReader(), dec=new TextDecoder();
    let buf='';
    for(;;){
      const {done, value}=await reader.read();
      if(done) break;
      buf+=dec.decode(value, {stream:true});
      const events=buf.split('\n\n'); buf=events.pop();
      for(const ev of events){
        const line=ev.split('\n').find(l=>l.startsWith('data: '));
        if(!line) continue;
        let d; try{ d=JSON.parse(line.slice(6)); }catch{ continue; }
        if(d.type==='content_block_start' && d.content_block?.type==='server_tool_use'){
          searched=true;
          a.innerHTML=marked.parse(answer)
            +'<span class="status">Searching the docs…</span>';
        }else if(d.type==='content_block_delta' && d.delta?.type==='text_delta'){
          answer+=d.delta.text;
          a.innerHTML=marked.parse(answer);
        }else if(d.type==='error'){
          throw new Error(d.error?.message || 'stream error');
        }
        chat.scrollTop=chat.scrollHeight;
      }
    }
    a.innerHTML=marked.parse(answer || '_(no reply)_');
    history.push({role:'assistant', content:[{type:'text', text:answer}]});
    // Stream 2 of the feedback loop: questions the assistant had to search for
    // are candidate gaps in the guide (assistant/spec.md).
    if(searched && text) sendFeedback('assistant-searched', text);
  }catch(err){
    history.pop(); // let the user retry the same question
    a.innerHTML='<span class="status">'+
      (String(err.message).includes('not configured')
        ? 'The assistant isn\'t connected on this deployment yet (missing API key).'
        : 'Something went wrong: '+err.message+' — try again.')
      +'</span>';
    if(text) sendFeedback('assistant-error', err.message+' — q: '+text);
  }finally{
    busy=false;
    chat.scrollTop=chat.scrollHeight;
  }
}

buildNav();
greet();
addEventListener('hashchange', ()=>render(location.hash.slice(1)));
render(location.hash.slice(1) || '00-start-here.md');
</script>
</body>
</html>
"""

OUT.write_text(HTML.replace("__DATA__", DATA), encoding="utf-8")
print(f"wrote {OUT} ({len(content)} pages)")
print(f"wrote {GUIDE_JS} ({len(system_prompt)} chars of system prompt)")
