#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Regenerate the workspace's managed blocks from the live worktree.

`best` is one Git repo with a few nested repos. This walks the tree, discovers those
nested repos directly (no checked-in manifest), and rewrites: each parent's managed
`.gitignore` block, the per-parent **Sub-repositories** tables, the root **Questions**
map, and the `.gitkeep` files that keep sub-repo paths from vanishing.

Privacy is the one thing that can't be derived — it's human judgment about what's about
others or holds credentials — so it lives by hand in `ai/private-paths`.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANAGED_BEGIN = "# BEGIN managed repo folders"
MANAGED_END = "# END managed repo folders"
MANAGED_NOTE = "# Generated by ai/sync-repos.py. Do not edit by hand."

PRIVATE_PATHS = ROOT / "ai" / "private-paths"
MAP_BEGIN = "<!-- BEGIN managed repo map -->"
MAP_END = "<!-- END managed repo map -->"
MAP_NOTE = "<!-- Generated by ai/sync-repos.py. Do not edit by hand. -->"
QMAP_BEGIN = "<!-- BEGIN managed question map -->"
QMAP_END = "<!-- END managed question map -->"
QMAP_NOTE = (
    "<!-- Generated by ai/sync-repos.py from each folder's README.md first line. "
    "Do not edit by hand. -->"
)
# Directory names the question map never descends into.
QMAP_SKIP = {".git", "__pycache__", "node_modules", ".astro", "dist"}
QMAP_MAX_DEPTH = 1  # top-level folders and their direct children
SUBREPO_NOTE = (
    "These folders are separate Git repos, not tracked here — git can't reach across a "
    "nested `.git`, so open a link to see a folder's files. (Private links 404 without access.)"
)
ROOT_INTRO = """# best

My life-optimization workspace.

I'm a Toby Ord utilitarian. I take that to mean: there's a set of questions about
what's best — the best act, motive, trait, work, life — that we can keep asking
ourselves and each other, and that I want to hold my best tentative answers to and act
from, to make outcomes as good as possible. So this runs as a practice — **every folder
is a standing question, every leaf a tentative answer.**

Two moves I keep making, usable inside any folder:

- **`other/`** — when a category collapses into its current answers, ask what *other*
  ways there are to do this. Keeps the question bigger than my answers.
- **`later/`** — what's worth returning to, but not now. A question I'm choosing to
  defer, not a parking lot.

The **Questions** map below is those standing questions, generated from each folder's
`README.md`, so it always mirrors the live worktree. A few folders stay their own Git
repos (private, or standalone) and are listed under **Sub-repositories**."""


def run_git(repo: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def is_ignored(parent: Path, name: str) -> bool:
    """Does the repo containing `parent` ignore the child directory `name`? (git resolves
    `-C parent` to whichever repo owns it, so nested repos each answer for their own tree.)"""
    return run_git(parent, "check-ignore", "-q", name).returncode == 0


def discover_repos() -> list[Path]:
    """Every nested repo under best, EXCEPT inside a directory its own repo ignores.

    A nested repo is always recorded — a parent ignores its children's contents, so
    "ignored" alone can't mean "hide it" (that's just how nesting works). But a plain
    ignored *non-repo* directory is scratch — a one-off's cloned working copies, build
    output — so we don't descend into it. This keeps a nested repo's own curated
    sub-repos on the map (e.g. `work/tools`'s installed tools) while keeping its
    throwaway working dirs (e.g. a migration's `repos/` full of clones) off it."""
    repos: list[Path] = []
    for current, dirs, files in os.walk(ROOT):
        path = Path(current)
        if path != ROOT and (path / ".git").exists():
            repos.append(path)

        kept: list[str] = []
        for d in dirs:
            if d in {".git", "__pycache__"}:
                continue
            if (path / d / ".git").exists():
                kept.append(d)  # a nested repo — always follow and record it
            elif is_ignored(path, d):
                continue  # ignored non-repo dir — scratch, don't descend
            else:
                kept.append(d)
        dirs[:] = kept

    return sorted(repos, key=lambda p: rel(p))


def origin_url(repo: Path) -> str | None:
    result = run_git(repo, "remote", "get-url", "origin")
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def nearest_parent(repo: Path, repos: list[Path]) -> Path:
    parent = ROOT
    for candidate in [ROOT, *repos]:
        if candidate == repo:
            continue
        try:
            repo.relative_to(candidate)
        except ValueError:
            continue
        if len(candidate.parts) > len(parent.parts):
            parent = candidate
    return parent


def build_entries(repos: list[Path]) -> list[dict[str, str | None]]:
    """Discover nested repos directly into the entry dicts the generators consume —
    path (best-relative), parent (`.` or best-relative), and origin remote."""
    entries: list[dict[str, str | None]] = []
    for repo in repos:
        parent = nearest_parent(repo, repos)
        entries.append(
            {
                "path": rel(repo),
                "parent": "." if parent == ROOT else rel(parent),
                "remote": origin_url(repo),
            }
        )
    return entries


def parent_patterns(entries: list[dict[str, str | None]]) -> dict[Path, list[str]]:
    grouped: dict[Path, list[str]] = {}
    for entry in entries:
        raw_path = entry.get("path")
        if not raw_path:
            continue
        raw_parent = entry.get("parent") or "."
        parent = ROOT if raw_parent == "." else ROOT / raw_parent
        child = Path(raw_path)
        if raw_parent != ".":
            child = child.relative_to(raw_parent)
        grouped.setdefault(parent, []).append(child.as_posix() + "/")
    return {parent: sorted(set(patterns)) for parent, patterns in grouped.items()}


def replace_managed_block(existing: str, patterns: list[str]) -> str:
    block_re = re.compile(
        rf"\n?{re.escape(MANAGED_BEGIN)}\n.*?{re.escape(MANAGED_END)}\n?",
        re.DOTALL,
    )
    base = block_re.sub("\n", existing).strip("\n")
    block = "\n".join([MANAGED_BEGIN, MANAGED_NOTE, *patterns, MANAGED_END])
    if base:
        return f"{base}\n\n{block}\n"
    return f"{block}\n"


def desired_ignores(entries: list[dict[str, str | None]]) -> dict[Path, str]:
    desired: dict[Path, str] = {}
    for parent, patterns in parent_patterns(entries).items():
        ignore = parent / ".gitignore"
        existing = ignore.read_text() if ignore.exists() else ""
        desired[ignore] = replace_managed_block(existing, patterns)
    return desired


def browsable(remote: str | None) -> str | None:
    if not remote:
        return None
    return re.sub(r"\.git$", "", remote)


def owner_repo(remote: str | None) -> str | None:
    if not remote:
        return None
    match = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?/?$", remote)
    return match.group(1) if match else remote


def private_prefixes() -> list[str]:
    if not PRIVATE_PATHS.exists():
        return []
    prefixes: list[str] = []
    for line in PRIVATE_PATHS.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            prefixes.append(line.strip("/"))
    return prefixes


def is_private(path: str, private: list[str]) -> bool:
    # Exact match: visibility reflects the linked repo itself, not its container. A
    # private repo's own path is listed; a public (e.g. third-party) repo nested inside
    # a private one is still its own accessible repo, so it isn't marked private.
    return path in private


def build_subrepo_table(
    children: list[dict[str, str | None]], parent: str, prefixes: list[str]
) -> str:
    rows = ["| Folder | Visibility | Repository |", "|---|---|---|"]
    for entry in sorted(children, key=lambda e: e["path"] or ""):
        full = entry["path"] or ""
        rel = full if parent == "." else Path(full).relative_to(parent).as_posix()
        url = browsable(entry.get("remote"))
        slug = owner_repo(entry.get("remote")) or rel
        link = f"[{slug}]({url})" if url else slug
        vis = "🔒 private" if is_private(full, prefixes) else "public"
        rows.append(f"| `{rel}/` | {vis} | {link} |")
    return "\n".join(rows)


README_ROOT = ROOT / "README.md"


def readme_path(parent: str) -> Path:
    return README_ROOT if parent == "." else ROOT / parent / "README.md"


def folder_question(folder: Path) -> str | None:
    """The first non-empty line of a folder's README.md — its standing question."""
    readme = folder / "README.md"
    if not readme.exists():
        return None
    for line in readme.read_text().splitlines():
        line = line.strip()
        if line:
            return line.lstrip("#").strip()
    return None


def build_question_map() -> str:
    """Nested bullets of every folder that states a question (README.md first line),
    each ending with its full path. Descends the live worktree, so the map can't drift
    from it; stops at nested repos and at QMAP_MAX_DEPTH to stay a map, not a listing."""
    lines: list[str] = []

    def walk(folder: Path, depth: int) -> None:
        if depth > QMAP_MAX_DEPTH:
            return
        children = sorted(
            (
                c
                for c in folder.iterdir()
                if c.is_dir()
                and not c.is_symlink()
                and c.name not in QMAP_SKIP
                and not c.name.startswith(".")
            ),
            key=lambda p: p.name,
        )
        for child in children:
            question = folder_question(child)
            if question:
                lines.append(f"{'  ' * depth}- {question} — `{rel(child)}`")
            if not (child / ".git").exists():
                walk(child, depth + 1)

    walk(ROOT, 0)
    return "\n".join(lines)


def desired_readmes(entries: list[dict[str, str | None]]) -> dict[Path, str]:
    prefixes = private_prefixes()
    by_parent: dict[str, list[dict[str, str | None]]] = {}
    for entry in entries:
        if not entry.get("path"):
            continue
        by_parent.setdefault(entry.get("parent") or ".", []).append(entry)

    block_re = re.compile(
        rf"\n?{re.escape(MAP_BEGIN)}\n.*?{re.escape(MAP_END)}\n?",
        re.DOTALL,
    )
    qmap_re = re.compile(
        rf"\n?{re.escape(QMAP_BEGIN)}\n.*?{re.escape(QMAP_END)}\n?",
        re.DOTALL,
    )
    desired: dict[Path, str] = {}
    for parent, children in by_parent.items():
        readme = readme_path(parent)
        block = "\n".join(
            [
                MAP_BEGIN,
                MAP_NOTE,
                "",
                "## Sub-repositories",
                "",
                SUBREPO_NOTE,
                "",
                build_subrepo_table(children, parent, prefixes),
                MAP_END,
            ]
        )
        existing = readme.read_text() if readme.exists() else ""
        base = qmap_re.sub("\n", block_re.sub("\n", existing)).strip("\n")
        if not base:
            base = ROOT_INTRO.strip("\n") if parent == "." else f"# {Path(parent).name}"
        # The root README also carries the question map, above the sub-repo table.
        if parent == ".":
            qmap_block = "\n".join(
                [QMAP_BEGIN, QMAP_NOTE, "", "## Questions", "", build_question_map(), QMAP_END]
            )
            desired[readme] = f"{base}\n\n{qmap_block}\n\n{block}\n"
        else:
            desired[readme] = f"{base}\n\n{block}\n"
    return desired


def desired_gitkeeps(entries: list[dict[str, str | None]]) -> set[Path]:
    """A `.gitkeep` for any folder whose only visible content is nested repos, so the
    path down to a sub-repo never vanishes (git tracks no empty directory)."""
    by_folder: dict[Path, set[str]] = {}
    for entry in entries:
        child = Path(entry["path"] or "")
        by_folder.setdefault(child.parent, set()).add(child.name)

    keeps: set[Path] = set()
    for rel_folder, subrepos in by_folder.items():
        if rel_folder == Path("."):
            continue
        folder = ROOT / rel_folder
        if not folder.is_dir():
            continue
        others = [
            item.name
            for item in folder.iterdir()
            if item.name not in subrepos
            and item.name != ".gitkeep"
            and not item.name.startswith(".")
        ]
        if not others:
            keeps.add(folder / ".gitkeep")
    return keeps


def find_gitmodules() -> list[Path]:
    found: list[Path] = []
    for path in ROOT.rglob(".gitmodules"):
        if ".git" not in path.parts:
            found.append(path)
    return sorted(found)


def find_gitlinks(repos: list[Path]) -> dict[Path, list[str]]:
    gitlinks: dict[Path, list[str]] = {}
    for repo in [ROOT, *repos]:
        result = run_git(repo, "ls-files", "-s")
        if result.returncode != 0:
            continue
        links = [
            line.rsplit("\t", 1)[-1]
            for line in result.stdout.splitlines()
            if line.startswith("160000 ")
        ]
        if links:
            gitlinks[repo] = links
    return gitlinks


def write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text() if path.exists() else None
    if old == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def write() -> int:
    repos = discover_repos()
    entries = build_entries(repos)
    changed: list[str] = []

    for path, content in desired_ignores(entries).items():
        if write_if_changed(path, content):
            changed.append(path.relative_to(ROOT).as_posix())

    for path, content in desired_readmes(entries).items():
        if write_if_changed(path, content):
            changed.append(path.relative_to(ROOT).as_posix())

    for keep in desired_gitkeeps(entries):
        if not keep.exists():
            keep.write_text("")
            changed.append(keep.relative_to(ROOT).as_posix())

    if changed:
        print("updated:")
        for path in sorted(changed):
            print(f"  {path}")
    else:
        print("generated blocks are current")
    return 0


def check() -> int:
    repos = discover_repos()
    entries = build_entries(repos)
    failures: list[str] = []

    for path, expected in desired_ignores(entries).items():
        if not path.exists() or path.read_text() != expected:
            failures.append(
                f"{path.relative_to(ROOT).as_posix()} generated block is stale; "
                "run `ai/sync-repos.py`."
            )

    for path, expected in desired_readmes(entries).items():
        if not path.exists() or path.read_text() != expected:
            failures.append(
                f"{path.relative_to(ROOT).as_posix()} sub-repo map is stale; "
                "run `ai/sync-repos.py`."
            )

    for keep in desired_gitkeeps(entries):
        if not keep.exists():
            failures.append(
                f"{keep.relative_to(ROOT).as_posix()} is missing; run `ai/sync-repos.py`."
            )

    gitmodules = find_gitmodules()
    if gitmodules:
        paths = ", ".join(path.relative_to(ROOT).as_posix() for path in gitmodules)
        failures.append(f"submodule metadata remains: {paths}")

    gitlinks = find_gitlinks(repos)
    for repo, links in gitlinks.items():
        label = "." if repo == ROOT else repo.relative_to(ROOT).as_posix()
        failures.append(f"{label} still tracks gitlinks: {', '.join(links)}")

    if failures:
        for failure in failures:
            print(f"repo sync check: {failure}", file=sys.stderr)
        return 1

    print("repo sync check passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated blocks, gitkeeps, or submodule state are stale",
    )
    args = parser.parse_args()
    return check() if args.check else write()


if __name__ == "__main__":
    raise SystemExit(main())
