#!/usr/bin/env python3
"""Rebuild readings/INDEX.md from each reading's frontmatter.

Usage: python3 build_index.py <readings_dir>
"""
import os
import re
import sys


def field(text, name):
    m = re.search(rf'^{name}: "?(.*?)"?$', text[:2000], re.M)
    return m.group(1).strip() if m else ""


def main():
    root = sys.argv[1]
    clusters = {}
    for dirpath, _, files in os.walk(root):
        for f in sorted(files):
            if not f.endswith(".md") or f == "INDEX.md":
                continue
            path = os.path.join(dirpath, f)
            rel = os.path.relpath(path, root)
            cluster = rel.split(os.sep)[0] if os.sep in rel else "(root)"
            text = open(path, encoding="utf-8", errors="replace").read()
            clusters.setdefault(cluster, []).append({
                "rel": rel,
                "title": field(text, "title") or f,
                "author": field(text, "author"),
                "url": field(text, "url"),
                "note": field(text, "note"),
                "chars": len(text),
            })
    out = ["# Readings index", "", "Generated by history/build_index.py — do not edit by hand.", ""]
    total = sum(len(v) for v in clusters.values())
    out.append(f"{total} readings in {len(clusters)} clusters.")
    out.append("")
    for cluster in sorted(clusters):
        rows = clusters[cluster]
        out.append(f"## {cluster} ({len(rows)})")
        out.append("")
        for r in sorted(rows, key=lambda r: r["rel"]):
            author = f" — {r['author']}" if r["author"] else ""
            note = f" — {r['note']}" if r["note"] else ""
            flag = " ⚠️short" if r["chars"] < 1500 else ""
            out.append(f"- [{r['title']}]({r['rel']}){author} ([source]({r['url']})){note}{flag}")
        out.append("")
    open(os.path.join(root, "INDEX.md"), "w").write("\n".join(out))
    print(f"INDEX.md: {total} readings, {len(clusters)} clusters")


if __name__ == "__main__":
    main()
